import { Noto_Serif } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body className="antialiased" cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
